source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'data_active', '0.0.6'
gem 'nokogiri'

group :test do
  gem 'cucumber'
  gem 'guard-cucumber'
  gem 'growl_notify'
  gem 'database_cleaner'
  gem 'linecache19', '~> 0.5.13', :git => 'https://github.com/ucberkeley/linecache19.git'
  gem 'ruby-debug-base19x', '0.11.30.pre11'
  gem 'ruby-debug-ide', '0.4.17.beta16'
end

gem 'rspec-rails', '~> 2.0', :groups => [:test, :development]
gem 'cucumber-rails', '>= 1.3.0', :group => :test, :require => false



# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
#gem 'ruby-debug19', :require => 'ruby-debug'
