#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'cucumber/rake/task'

BookStore::Application.load_tasks

Cucumber::Rake::Task.new(:cucumber) do |test|
  ENV['APP_ENV'] = "test" if ENV['APP_ENV'].nil?
end

task :default => :cucumber
